/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Compute the next state for a given transition.
 *
 * JS signature: `nextState(from: string | null, transition: string) -> string`
 *
 * Throws if `transition` is unknown OR if the transition is illegal from `from`.
 * The error message includes both `from` and `transition` so the caller can
 * surface it directly.
 */
export declare function nextState(from: string | undefined | null, transition: string): string
/** Classifier — is the given state terminal (no outgoing transitions)? */
export declare function isTerminal(state: string): boolean
/** Classifier — is the given state in-flight (mid-transition; subject to crash recovery)? */
export declare function isInFlight(state: string): boolean
/** Crate version — handy for debugging which binding is loaded. */
export declare function version(): string
/**
 * Canonical JSON: keys sorted alphabetically at every depth. Input is a
 * JSON-encoded string (caller does `JSON.stringify(obj)` first), output
 * is the canonical form.
 *
 * Produces byte-identical output to `canonicalJson` in
 * `Mafia/src/quarantine/reflog.ts`.
 */
export declare function canonicalJson(valueJson: string): string
/**
 * One reflog entry. Shape mirrors `Mafia/src/quarantine/types.ts`
 * `ReflogEntry`. Snake_case names match the SQLite columns + TS interface.
 *
 * Note: napi exposes `seq` and `ts` as JS `number` (f64) — this fits all
 * realistic values (seq < 2^53, ts in seconds also < 2^53). At the FFI
 * boundary we cast to i64 for the core crate.
 */
export interface JsReflogEntry {
  seq: number
  prevHash: string
  entryHash: string
  ts: number
  userId: string
  actionId: string
  transition: string
  payloadJson: string
}
/**
 * Result of `verifyChain`. `ok=true` means the chain is intact.
 * On failure, `brokenAt` is the `seq` of the first invalid entry and
 * `reason` describes why.
 */
export interface JsVerifyResult {
  ok: boolean
  brokenAt?: number
  reason?: string
}
/**
 * Verify a reflog chain. Entries MUST be in ascending `seq` order.
 * The TS caller does `SELECT * FROM reflog ORDER BY seq ASC` then passes
 * the rows here.
 */
export declare function verifyChain(entries: Array<JsReflogEntry>): JsVerifyResult
